import type { EditableField, GalleryItem, StoryChapter, WeddingContent } from "@/types/wedding";

const pending = <T>(placeholder: string): EditableField<T> => ({ value: null, status: "pending", placeholder });
const confirmed = <T>(value: T, placeholder = ""): EditableField<T> => ({ value, status: "confirmed", placeholder });

const storyPlaceholder = (id: string, alignment: StoryChapter["alignment"]): StoryChapter => ({
  id,
  date: pending("Data do capítulo a definir"),
  title: pending("Título do capítulo a definir"),
  body: pending("Texto da história do casal a ser fornecido"),
  image: pending("Fotografia do casal a ser adicionada"),
  imageAlt: "Espaço reservado para uma fotografia de Maria e Sérgio",
  caption: pending("Legenda da fotografia a definir"),
  alignment,
});

const galleryPlaceholder = (id: string, aspectRatio: GalleryItem["aspectRatio"]): GalleryItem => ({
  id,
  src: pending("Fotografia a ser adicionada"),
  alt: "Espaço reservado para uma fotografia de Maria e Sérgio",
  caption: pending("Legenda da fotografia a definir"),
  aspectRatio,
});

export const weddingContent = {
  couple: { firstName: "Maria", secondName: "Sérgio", displayName: "Maria & Sérgio" },
  date: {
    isoDate: "2026-10-31",
    displayLong: "31 de outubro de 2026",
    displayShort: "31 · 10 · 2026",
    timeZone: "America/Fortaleza",
    ceremonyTime: pending("Horário da cerimônia a confirmar"),
    receptionTime: pending("Horário da recepção a confirmar"),
  },
  metadata: {
    title: "Maria & Sérgio — 31 de outubro de 2026",
    description: "Convite de casamento de Maria e Sérgio, em 31 de outubro de 2026.",
    canonicalUrl: pending("Domínio oficial a definir"),
    openGraphImage: "/images/save-the-date.png",
    themeColor: "#747b55",
  },
  assets: {
    monogram: {
      src: "/images/monogram.png",
      alt: "Monograma de Maria e Sérgio",
      width: 1240,
      height: 960,
      status: "confirmed",
    },
    saveTheDate: {
      src: "/images/save-the-date.png",
      alt: "Save the date de Maria e Sérgio, 31 de outubro de 2026, com ilustração em aquarela de uma igreja à beira-mar",
      width: 1080,
      height: 1436,
      status: "confirmed",
    },
  },
  audio: {
    enabled: false,
    src: "/audio/maria-e-sergio-theme.mp3",
    title: "Trilha de Maria e Sérgio",
    missingMessage: "A trilha será adicionada em breve.",
  },
  navigation: [
    { label: "Início", href: "#inicio" },
    { label: "Nossa história", href: "#historia" },
    { label: "Celebração", href: "#celebracao" },
    { label: "Programação", href: "#programacao" },
    { label: "Traje", href: "#traje" },
    { label: "Galeria", href: "#galeria" },
    { label: "RSVP", href: "#rsvp" },
    { label: "Presentes", href: "#presentes" },
  ],
  opening: {
    instructionPointer: "Deslize para abrir o convite",
    instructionTouch: "Toque ou deslize para abrir",
    instructionKeyboard: "Pressione Enter ou Espaço para abrir",
    accessibleButton: "Abrir convite de Maria e Sérgio",
    openedAnnouncement: "Convite aberto",
    sessionStorageKey: "maria-sergio-invitation-open",
  },
  hero: {
    eyebrow: "Save the Date",
    title: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    location: "Cabedelo · Paraíba",
  },
  announcement: {
    eyebrow: "Vamos celebrar",
    title: "Um dia para guardar",
    invitation: "Reserve esta data para celebrar o casamento de Maria e Sérgio.",
    countdownLabels: { days: "dias", hours: "horas", minutes: "minutos", seconds: "segundos" },
    countdownComplete: "Chegou o nosso dia.",
  },
  story: {
    eyebrow: "Nossa história",
    title: "Capítulos que nos trouxeram até aqui",
    introduction: pending("O texto de abertura da história será incluído pelos noivos."),
    chapters: [
      storyPlaceholder("capitulo-1", "start"),
      storyPlaceholder("capitulo-2", "end"),
      storyPlaceholder("capitulo-3", "start"),
    ],
  },
  venues: [
    {
      id: "ceremony",
      eyebrow: "Cerimônia",
      name: "Paróquia Nossa Senhora de Nazaré",
      city: confirmed("Cabedelo"),
      region: confirmed("Paraíba"),
      time: pending("Horário a confirmar"),
      address: confirmed("Avenida Coronel Cardoso, 15 — Portal do Poço, Cabedelo"),
      note: pending("Informações adicionais serão incluídas em breve"),
      directionsUrl: pending("Link de rota a adicionar"),
      directionsLabel: "Como chegar",
      illustration: confirmed("/images/save-the-date.png"),
    },
    {
      id: "reception",
      eyebrow: "Recepção",
      name: "Buffet Doce Mel",
      city: confirmed("João Pessoa"),
      region: confirmed("Paraíba"),
      time: pending("Horário a confirmar"),
      address: confirmed("Rua Manuel Miguel Morais, 54 — Bancários, João Pessoa"),
      note: pending("Informações adicionais serão incluídas em breve"),
      directionsUrl: pending("Link de rota a adicionar"),
      directionsLabel: "Como chegar",
      illustration: pending("Imagem da recepção a adicionar"),
    },
  ],
  schedule: {
    eyebrow: "Programação",
    title: "O ritmo da celebração",
    items: [
      {
        id: "cerimonia",
        time: pending("Horário a confirmar"),
        title: "Cerimônia",
        description: confirmed("Paróquia Nossa Senhora de Nazaré"),
        icon: "church",
      },
      {
        id: "recepcao",
        time: pending("Horário a confirmar"),
        title: "Recepção",
        description: confirmed("Buffet Doce Mel"),
        icon: "celebration",
      },
    ],
  },
  dressCode: {
    eyebrow: "Traje",
    title: "Para celebrar conosco",
    introduction: pending("A orientação geral de traje será confirmada pelos noivos."),
    groups: [
      { id: "general", label: "Traje geral", guidance: pending("Orientação de traje geral a confirmar") },
      { id: "bridesmaids", label: "Madrinhas", guidance: confirmed("Vestido longo em tom verde oliva ou similar.") },
      { id: "groomsmen", label: "Padrinhos", guidance: confirmed("Terno cinza claro, camisa clara e gravata verde oliva.") },
      { id: "guests", label: "Convidados", guidance: pending("Orientação para convidados a confirmar") },
    ],
    notes: pending("Observações adicionais sobre o traje a confirmar"),
    swatches: [
      { name: "Verde oliva", colorToken: "olive" },
      { name: "Cinza claro", colorToken: "warm-gray-light" },
      { name: "Marfim", colorToken: "ivory" },
    ],
  },
  gallery: {
    eyebrow: "Galeria",
    title: "Memórias em construção",
    introduction: pending("As fotografias do casal serão adicionadas a esta composição editorial."),
    items: [
      galleryPlaceholder("foto-1", "portrait"),
      galleryPlaceholder("foto-2", "landscape"),
      galleryPlaceholder("foto-3", "square"),
      galleryPlaceholder("foto-4", "portrait"),
      galleryPlaceholder("foto-5", "landscape"),
      galleryPlaceholder("foto-6", "portrait"),
    ],
  },
  rsvp: {
    eyebrow: "Confirmação",
    title: "RSVP",
    introduction: "A integração de confirmação será disponibilizada quando o canal oficial for definido.",
    modeEnvironmentVariable: "NEXT_PUBLIC_RSVP_MODE",
    endpointEnvironmentVariable: "NEXT_PUBLIC_RSVP_ENDPOINT",
    defaultMode: "demo",
    maxGuests: pending<number>("Limite de acompanhantes a confirmar"),
    labels: {
      firstName: "Nome",
      lastName: "Sobrenome",
      phone: "Telefone",
      email: "E-mail (opcional)",
      guestCount: "Quantidade de convidados",
      attendance: "Você poderá comparecer?",
      attendanceYes: "Sim, estarei presente",
      attendanceNo: "Não poderei comparecer",
      dietaryRestrictions: "Restrições alimentares",
      message: "Mensagem para os noivos",
      submit: "Enviar confirmação",
      submitting: "Enviando...",
    },
    messages: {
      required: "Preencha este campo.",
      invalidEmail: "Informe um e-mail válido.",
      invalidPhone: "Informe um telefone válido.",
      invalidGuestCount: "Informe uma quantidade válida de convidados.",
      demo: "Modo de demonstração: os dados foram validados, mas não foram enviados nem salvos.",
      success: "Confirmação enviada com sucesso.",
      endpointMissing: "O canal de confirmação ainda não está configurado. Nenhum dado foi enviado.",
      genericError: "Não foi possível enviar a confirmação. Tente novamente mais tarde.",
    },
  },
  gifts: {
    eyebrow: "Presentes",
    title: "Um gesto de carinho",
    message: pending("A mensagem da lista de presentes será fornecida pelos noivos."),
    platform: pending("Plataforma de casamento a definir"),
    stores: [],
    pendingMessage: "Os links da lista de presentes serão adicionados em breve.",
  },
  travel: {
    enabled: false,
    eyebrow: "Viagem e hospedagem",
    title: "Para quem vem de longe",
    introduction: pending("Introdução de viagem e hospedagem a definir"),
    airport: pending("Informações de aeroporto a definir"),
    transportation: pending("Informações de deslocamento a definir"),
    hotels: pending<string[]>("Sugestões de hospedagem a definir"),
    beaches: pending<string[]>("Informações sobre praias a definir"),
    recommendations: pending<string[]>("Recomendações locais a definir"),
    contact: pending("Contato de apoio a definir"),
  },
  closing: {
    eyebrow: "Com carinho",
    thankYou: "Agradecemos por fazer parte deste momento.",
    names: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    calendar: {
      allDay: true,
      eventTitle: "Casamento de Maria e Sérgio",
      description: confirmed("Celebração do casamento de Maria e Sérgio."),
      location: confirmed("Paróquia Nossa Senhora de Nazaré, Cabedelo, Paraíba"),
      googleCalendarUrl: pending("Gerado pela interface a partir dos dados confirmados"),
      downloadLabel: "Adicionar ao calendário",
    },
    shareLabel: "Compartilhar convite",
    copyLinkSuccess: "Link do convite copiado.",
    backToTopLabel: "Voltar ao início",
  },
  personalization: {
    enabled: false,
    allowedQueryParameters: { guestName: "convidado", invitationCode: "convite", maximumCompanions: "acompanhantes" },
  },
  features: {
    showStory: true,
    showSchedule: true,
    showDressCode: true,
    showGallery: true,
    showRsvp: true,
    showGifts: true,
    showTravel: false,
    showAudioControl: true,
  },
} satisfies WeddingContent;

export default weddingContent;
