import type { EditableField, WeddingContent } from "@/types/wedding";

const pending = <T>(placeholder: string): EditableField<T> => ({ value: null, status: "pending", placeholder });
const confirmed = <T>(value: T, placeholder = ""): EditableField<T> => ({ value, status: "confirmed", placeholder });

export const weddingContent = {
  couple: { firstName: "Maria", secondName: "Sérgio", displayName: "Maria & Sérgio" },
  date: {
    isoDate: "2026-10-31",
    displayLong: "31 de outubro de 2026",
    displayShort: "31 · 10 · 2026",
    timeZone: "America/Fortaleza",
    ceremonyTime: pending("Horário da cerimônia a confirmar"),
    receptionTime: pending("Horário da recepção a confirmar"),
  },
  metadata: {
    title: "Maria & Sérgio — 31 de outubro de 2026",
    description: "Convite de casamento de Maria e Sérgio, em 31 de outubro de 2026.",
    canonicalUrl: pending("Domínio oficial a definir"),
    openGraphImage: "/images/save-the-date.png",
    themeColor: "#747b55",
  },
  assets: {
    monogram: {
      src: "/images/monogram.png",
      alt: "Monograma de Maria e Sérgio",
      width: 1240,
      height: 960,
      status: "confirmed",
    },
    saveTheDate: {
      src: "/images/save-the-date.png",
      alt: "Save the date de Maria e Sérgio, 31 de outubro de 2026, com ilustração em aquarela de uma igreja à beira-mar",
      width: 1080,
      height: 1436,
      status: "confirmed",
    },
    heroPhoto: {
      src: "/images/wedding/preview/hero-embrace-architecture.jpg",
      alt: "Sérgio abraça Maria diante de uma fachada clássica, em um momento íntimo do ensaio.",
      width: 800,
      height: 1200,
      status: "confirmed",
    },
  },
  audio: {
    enabled: false,
    src: "/audio/maria-e-sergio-theme.mp3",
    title: "Trilha de Maria e Sérgio",
    missingMessage: "A trilha será adicionada em breve.",
  },
  navigation: [
    { label: "Início", href: "#inicio" },
    { label: "Nossa história", href: "#historia" },
    { label: "Celebração", href: "#celebracao" },
    { label: "Programação", href: "#programacao" },
    { label: "Traje", href: "#traje" },
    { label: "Galeria", href: "#galeria" },
    { label: "RSVP", href: "#rsvp" },
    { label: "Presentes", href: "#presentes" },
  ],
  opening: {
    instructionPointer: "Deslize para abrir o convite",
    instructionTouch: "Toque ou deslize para abrir",
    instructionKeyboard: "Pressione Enter ou Espaço para abrir",
    accessibleButton: "Abrir convite de Maria e Sérgio",
    openedAnnouncement: "Convite aberto",
    sessionStorageKey: "maria-sergio-invitation-open",
  },
  hero: {
    eyebrow: "Save the Date",
    title: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    location: "Cabedelo · Paraíba",
  },
  announcement: {
    eyebrow: "Vamos celebrar",
    title: "Um dia para guardar",
    invitation: "Reserve esta data para celebrar o casamento de Maria e Sérgio.",
    countdownLabels: { days: "dias", hours: "horas", minutes: "minutos", seconds: "segundos" },
    countdownComplete: "Chegou o nosso dia.",
  },
  story: {
    eyebrow: "Nossa história",
    title: "Capítulos que nos trouxeram até aqui",
    introduction: confirmed("Entre salões, jardins e silêncios de fim de tarde, algumas cenas já contam o caminho de Maria e Sérgio até este dia."),
    chapters: [
      {
        id: "capitulo-1",
        date: confirmed("O começo"),
        title: confirmed("Um encontro no ritmo certo"),
        body: confirmed("A escadaria abre a história com a solenidade de uma entrada, mas o gesto é íntimo: dois olhares, uma pausa e a certeza tranquila de estar junto."),
        image: confirmed("/images/wedding/preview/story-staircase-kiss.jpg"),
        imageAlt: "Maria e Sérgio se beijam em uma escadaria com tapete vermelho.",
        imageTreatment: { desktopPosition: "50% 22%", mobilePosition: "50% 20%", overlay: "ivory" },
        caption: confirmed("Uma cena vertical, reservada e cerimonial."),
        alignment: "start",
      },
      {
        id: "capitulo-2",
        date: confirmed("A caminhada"),
        title: confirmed("Dois passos na mesma direção"),
        body: confirmed("O salão claro e o piso antigo dão escala ao momento. Maria e Sérgio aparecem em movimento, como se a página respirasse junto com eles."),
        image: confirmed("/images/wedding/preview/story-palace-walk.jpg"),
        imageAlt: "Maria e Sérgio caminham de mãos dadas em um salão claro.",
        imageTreatment: { desktopPosition: "50% 20%", mobilePosition: "50% 18%", overlay: "none" },
        caption: confirmed("Movimento leve dentro de uma arquitetura clássica."),
        alignment: "end",
      },
      {
        id: "capitulo-3",
        date: confirmed("A promessa"),
        title: confirmed("Calma antes da celebração"),
        body: confirmed("Na varanda, o enquadramento fica mais próximo e contemplativo. A fotografia encerra a sequência com delicadeza, antes da celebração ganhar forma."),
        image: confirmed("/images/wedding/preview/story-balcony-quiet.jpg"),
        imageAlt: "Maria e Sérgio juntos em uma varanda, em um momento tranquilo.",
        imageTreatment: { desktopPosition: "50% 18%", mobilePosition: "50% 16%", overlay: "olive" },
        caption: confirmed("Um retrato íntimo para fechar a narrativa."),
        alignment: "start",
      },
    ],
  },
  venues: [
    {
      id: "ceremony",
      eyebrow: "Cerimônia",
      name: "Paróquia Nossa Senhora de Nazaré",
      city: confirmed("Cabedelo"),
      region: confirmed("Paraíba"),
      time: pending("Horário a confirmar"),
      address: confirmed("Avenida Coronel Cardoso, 15 — Portal do Poço, Cabedelo"),
      note: pending("Informações adicionais serão incluídas em breve"),
      directionsUrl: pending("Link de rota a adicionar"),
      directionsLabel: "Como chegar",
      illustration: confirmed("/images/save-the-date.png"),
    },
    {
      id: "reception",
      eyebrow: "Recepção",
      name: "Buffet Doce Mel",
      city: confirmed("João Pessoa"),
      region: confirmed("Paraíba"),
      time: pending("Horário a confirmar"),
      address: confirmed("Rua Manuel Miguel Morais, 54 — Bancários, João Pessoa"),
      note: pending("Informações adicionais serão incluídas em breve"),
      directionsUrl: pending("Link de rota a adicionar"),
      directionsLabel: "Como chegar",
      illustration: pending("Imagem da recepção a adicionar"),
    },
  ],
  schedule: {
    eyebrow: "Programação",
    title: "O ritmo da celebração",
    items: [
      {
        id: "cerimonia",
        time: pending("Horário a confirmar"),
        title: "Cerimônia",
        description: confirmed("Paróquia Nossa Senhora de Nazaré"),
        icon: "church",
      },
      {
        id: "recepcao",
        time: pending("Horário a confirmar"),
        title: "Recepção",
        description: confirmed("Buffet Doce Mel"),
        icon: "celebration",
      },
    ],
  },
  dressCode: {
    eyebrow: "Traje",
    title: "Para celebrar conosco",
    introduction: pending("A orientação geral de traje será confirmada pelos noivos."),
    groups: [
      { id: "general", label: "Traje geral", guidance: pending("Orientação de traje geral a confirmar") },
      { id: "bridesmaids", label: "Madrinhas", guidance: confirmed("Vestido longo em tom verde oliva ou similar.") },
      { id: "groomsmen", label: "Padrinhos", guidance: confirmed("Terno cinza claro, camisa clara e gravata verde oliva.") },
      { id: "guests", label: "Convidados", guidance: pending("Orientação para convidados a confirmar") },
    ],
    notes: pending("Observações adicionais sobre o traje a confirmar"),
    swatches: [
      { name: "Verde oliva", colorToken: "olive" },
      { name: "Cinza claro", colorToken: "warm-gray-light" },
      { name: "Marfim", colorToken: "ivory" },
    ],
  },
  gallery: {
    eyebrow: "Galeria",
    title: "Retratos de uma espera bonita",
    introduction: confirmed("Uma seleção curta, feita para variar distância, gesto e atmosfera sem transformar a página em um álbum completo."),
    items: [
      {
        id: "foto-1",
        src: confirmed("/images/wedding/preview/gallery-garden-embrace.jpg"),
        alt: "Maria e Sérgio abraçados em frente a uma fachada branca com vegetação.",
        caption: confirmed("Jardim e fachada branca"),
        aspectRatio: "portrait",
        treatment: { desktopPosition: "52% 44%", mobilePosition: "52% 34%", overlay: "ivory" },
      },
      {
        id: "foto-2",
        src: confirmed("/images/wedding/preview/gallery-bench-laughter.jpg"),
        alt: "Maria e Sérgio sentados em um banco, sorrindo juntos.",
        caption: confirmed("Um sorriso sem pose"),
        aspectRatio: "landscape",
        treatment: { desktopPosition: "50% 20%", mobilePosition: "50% 18%", overlay: "none" },
      },
      {
        id: "foto-3",
        src: confirmed("/images/wedding/preview/gallery-salon-distance.jpg"),
        alt: "Maria e Sérgio em um salão amplo, vistos à distância sob um lustre.",
        caption: confirmed("Escala e silêncio"),
        aspectRatio: "square",
        treatment: { desktopPosition: "50% 47%", mobilePosition: "50% 40%", overlay: "none" },
      },
      {
        id: "foto-4",
        src: confirmed("/images/wedding/preview/gallery-rooftop-lamp.jpg"),
        alt: "Maria e Sérgio juntos ao lado de um poste ornamental.",
        caption: confirmed("Linha, céu e abraço"),
        aspectRatio: "portrait",
        treatment: { desktopPosition: "50% 44%", mobilePosition: "50% 31%", overlay: "ivory" },
      },
      {
        id: "foto-5",
        src: confirmed("/images/wedding/preview/gallery-ballroom-motion.jpg"),
        alt: "Maria e Sérgio abraçados em um salão com piso listrado.",
        caption: confirmed("Movimento de salão"),
        aspectRatio: "landscape",
        treatment: { desktopPosition: "50% 21%", mobilePosition: "50% 18%", overlay: "none" },
      },
      {
        id: "foto-6",
        src: confirmed("/images/wedding/preview/gallery-mirror-embrace.jpg"),
        alt: "Maria e Sérgio abraçados diante de um espelho dourado.",
        caption: confirmed("O reflexo como moldura"),
        aspectRatio: "portrait",
        treatment: { desktopPosition: "50% 43%", mobilePosition: "50% 32%", overlay: "olive" },
      },
    ],
  },
  rsvp: {
    eyebrow: "Confirmação",
    title: "RSVP",
    introduction: "A integração de confirmação será disponibilizada quando o canal oficial for definido.",
    modeEnvironmentVariable: "NEXT_PUBLIC_RSVP_MODE",
    endpointEnvironmentVariable: "NEXT_PUBLIC_RSVP_ENDPOINT",
    defaultMode: "demo",
    maxGuests: pending<number>("Limite de acompanhantes a confirmar"),
    labels: {
      firstName: "Nome",
      lastName: "Sobrenome",
      phone: "Telefone",
      email: "E-mail (opcional)",
      guestCount: "Quantidade de convidados",
      attendance: "Você poderá comparecer?",
      attendanceYes: "Sim, estarei presente",
      attendanceNo: "Não poderei comparecer",
      dietaryRestrictions: "Restrições alimentares",
      message: "Mensagem para os noivos",
      submit: "Enviar confirmação",
      submitting: "Enviando...",
    },
    messages: {
      required: "Preencha este campo.",
      invalidEmail: "Informe um e-mail válido.",
      invalidPhone: "Informe um telefone válido.",
      invalidGuestCount: "Informe uma quantidade válida de convidados.",
      demo: "Modo de demonstração: os dados foram validados, mas não foram enviados nem salvos.",
      success: "Confirmação enviada com sucesso.",
      endpointMissing: "O canal de confirmação ainda não está configurado. Nenhum dado foi enviado.",
      genericError: "Não foi possível enviar a confirmação. Tente novamente mais tarde.",
    },
  },
  gifts: {
    eyebrow: "Presentes",
    title: "Lista de presentes",
    message: confirmed("A antiga lista dos noivos tinha humor próprio. Mantivemos o conteúdo e deixamos a apresentação conversar com a nova identidade visual."),
    platform: pending("Plataforma de casamento a definir"),
    stores: [],
    items: [
      { id: "aposentadoria", title: "Ajuda para a aposentadoria dos noivos", price: "R$3.194,99" },
      { id: "bebe", title: "Aluguel de um bebê para treinamento", price: "R$333,35" },
      { id: "frigobar", title: "Assaltar o frigobar na lua de mel", price: "R$271,18" },
      { id: "cobertor", title: "Cobertor para a noiva que está sempre coberta de razão", price: "R$120,94" },
      { id: "controles", title: "Conjunto de controle remotos para não ter briga", price: "R$209,01" },
      { id: "ar-condicionado", title: "Cota do ar condicionado pra não derreter nesse calor", price: "R$136,48" },
      { id: "filhos", title: "Cota para perguntar quando teremos filhos", price: "R$552,78" },
      { id: "geladeira", title: "Deus abençoou e você vai dar a geladeira", price: "R$3.143,19" },
      { id: "jantar-noivo", title: "Garanta o jantar do noivo durante o 1º mês de casado", price: "R$635,67" },
      { id: "buffet", title: "Garantir o primeiro lugar na fila do buffet", price: "R$177,92" },
      { id: "panelas", title: "Jogo de panelas para Sérgio sempre fazer o jantar", price: "R$157,20" },
      { id: "lava-seca", title: "Lava e seca pra não ter briga de quem estende a roupa", price: "R$1.278,09" },
      { id: "maquiagem", title: "Lenço para a noiva não borrar toda a maquiagem", price: "R$85,19" },
      { id: "maracuja", title: "Maracujá para os noivos ficarem tranquilos", price: "R$89,85" },
      { id: "financiamento", title: "Menos uma parcela no financiamento do AP", price: "R$967,25" },
      { id: "passeio", title: "Passeio na lua de mel", price: "R$428,44" },
      { id: "despedida-noiva", title: "Patrocine a despedida da noiva", price: "R$511,33" },
      { id: "despedida-noivo", title: "Patrocine a despedida do noivo", price: "R$473,00" },
      { id: "ir-junto", title: "Poder ir junto com os noivos para a lua de mel", price: "R$86.036,15" },
      { id: "presenteao", title: "Presentão para os noivos", price: "R$397,36" },
      { id: "quarto-visita", title: "Prioridade no quarto de visita na casa dos noivos", price: "R$791,10" },
      { id: "relogio", title: "Relógio para a noiva parar de se atrasar", price: "R$250,46" },
      { id: "tampao", title: "Tampão de ouvido pra noiva enquanto noivo ronca", price: "R$105,39" },
      { id: "buque", title: "Taxa pra noiva jogar o buquê na sua direção", price: "R$229,73" },
      { id: "cabelo", title: "Um ano de cabelo cortado para o noivo", price: "R$418,08" },
    ],
    pendingMessage: "Os links da lista de presentes serão adicionados em breve.",
  },
  travel: {
    enabled: false,
    eyebrow: "Viagem e hospedagem",
    title: "Para quem vem de longe",
    introduction: pending("Introdução de viagem e hospedagem a definir"),
    airport: pending("Informações de aeroporto a definir"),
    transportation: pending("Informações de deslocamento a definir"),
    hotels: pending<string[]>("Sugestões de hospedagem a definir"),
    beaches: pending<string[]>("Informações sobre praias a definir"),
    recommendations: pending<string[]>("Recomendações locais a definir"),
    contact: pending("Contato de apoio a definir"),
  },
  closing: {
    eyebrow: "Com carinho",
    thankYou: "Agradecemos por fazer parte deste momento.",
    names: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    calendar: {
      allDay: true,
      eventTitle: "Casamento de Maria e Sérgio",
      description: confirmed("Celebração do casamento de Maria e Sérgio."),
      location: confirmed("Paróquia Nossa Senhora de Nazaré, Cabedelo, Paraíba"),
      googleCalendarUrl: pending("Gerado pela interface a partir dos dados confirmados"),
      downloadLabel: "Adicionar ao calendário",
    },
    shareLabel: "Compartilhar convite",
    copyLinkSuccess: "Link do convite copiado.",
    backToTopLabel: "Voltar ao início",
  },
  personalization: {
    enabled: false,
    allowedQueryParameters: { guestName: "convidado", invitationCode: "convite", maximumCompanions: "acompanhantes" },
  },
  features: {
    showStory: true,
    showSchedule: true,
    showDressCode: true,
    showGallery: true,
    showRsvp: true,
    showGifts: true,
    showTravel: false,
    showAudioControl: true,
  },
} satisfies WeddingContent;

export default weddingContent;
