import type { EditableField, WeddingContent } from "@/types/wedding";

const pending = <T>(placeholder: string): EditableField<T> => ({ value: null, status: "pending", placeholder });
const confirmed = <T>(value: T, placeholder = ""): EditableField<T> => ({ value, status: "confirmed", placeholder });

export const weddingContent = {
  couple: { firstName: "Maria", secondName: "Sérgio", displayName: "Maria & Sérgio" },
  date: {
    isoDate: "2026-10-31",
    displayLong: "31 de outubro de 2026",
    displayShort: "31 · 10 · 2026",
    timeZone: "America/Fortaleza",
    ceremonyTime: confirmed("15:30"),
    receptionTime: pending(""),
  },
  metadata: {
    title: "Maria & Sérgio | 31.10.2026",
    description: "Nosso grande dia está chegando. Celebre conosco o casamento de Maria & Sérgio, em 31 de outubro de 2026.",
    canonicalUrl: confirmed("https://mariaesergio.com"),
    openGraphImage: "/images/social/maria-sergio-og.jpg",
    themeColor: "#747b55",
  },
  assets: {
    monogram: {
      src: "/images/monogram.png",
      alt: "Monograma de Maria e Sérgio",
      width: 1240,
      height: 960,
      status: "confirmed",
    },
    saveTheDate: {
      src: "/images/wedding/venues/ceremony-church-clean.png",
      alt: "Ilustração em aquarela da Paróquia Nossa Senhora de Nazaré.",
      width: 760,
      height: 720,
      status: "confirmed",
    },
    heroPhoto: {
      src: "/images/wedding/preview/hero-cover-fotoparaportada.jpeg",
      alt: "Maria e Sérgio se beijam diante de uma fachada branca, vestidos em tons claros.",
      width: 1080,
      height: 1600,
      status: "confirmed",
    },
    heroPhotoDesktop: {
      src: "/images/wedding/hero/hero-desktop.webp",
      alt: "Maria e Sérgio se beijam diante de uma fachada branca, vestidos em tons claros.",
      width: 2560,
      height: 1429,
      status: "confirmed",
    },
    heroPhotoMobile: {
      src: "/images/wedding/hero/hero-mobile.webp",
      alt: "Maria e Sérgio se beijam diante de uma fachada branca, vestidos em tons claros.",
      width: 1440,
      height: 1920,
      status: "confirmed",
    },
  },
  audio: {
    enabled: true,
    src: "/audio/maria-e-sergio-theme.mp3",
    spotifyUrl: "https://open.spotify.com/embed/track/6c6brFif6MTMSq0sVwgMAT?utm_source=generator&theme=0&si=e4289c78d01342fd",
    spotifyUri: "spotify:track:6c6brFif6MTMSq0sVwgMAT",
    title: "Beija Flor — João Gomes",
    missingMessage: "A trilha será adicionada em breve.",
  },
  navigation: [
    { label: "Início", href: "#inicio" },
    { label: "Celebração", href: "#celebracao" },
    { label: "Traje", href: "#traje" },
    { label: "RSVP", href: "#rsvp" },
    { label: "Presentes", href: "#presentes" },
  ],
  opening: {
    instructionPointer: "Deslize para abrir o convite",
    instructionTouch: "Toque ou deslize para abrir",
    instructionKeyboard: "Pressione Enter ou Espaço para abrir",
    accessibleButton: "Abrir convite de Maria e Sérgio",
    openedAnnouncement: "Convite aberto",
    sessionStorageKey: "maria-sergio-invitation-open",
  },
  hero: {
    eyebrow: "NOSSO SIM",
    title: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    location: "Cabedelo · Paraíba",
  },
  announcement: {
    eyebrow: "ESTÁ CHEGANDO",
    title: "Falta pouco para celebrarmos juntos",
    invitation: "Estamos contando os dias — e felizes por saber que você fará parte deles.",
    countdownLabels: { days: "dias", hours: "horas", minutes: "minutos", seconds: "segundos" },
    countdownComplete: "Chegou o nosso dia.",
  },
  story: {
    eyebrow: "Nossa história",
    title: "Capítulos que nos trouxeram até aqui",
    introduction: confirmed("Entre salões, jardins e silêncios de fim de tarde, algumas cenas já contam o caminho de Maria e Sérgio até este dia."),
    chapters: [
      {
        id: "capitulo-1",
        date: confirmed("O começo"),
        title: confirmed("Um encontro no ritmo certo"),
        body: confirmed("A escadaria abre a história com a solenidade de uma entrada, mas o gesto é íntimo: dois olhares, uma pausa e a certeza tranquila de estar junto."),
        image: confirmed("/images/wedding/preview/story-staircase-kiss.jpg"),
        imageAlt: "Maria e Sérgio se beijam em uma escadaria com tapete vermelho.",
        imageTreatment: { desktopPosition: "50% 22%", mobilePosition: "50% 20%", overlay: "ivory" },
        caption: confirmed("Uma cena vertical, reservada e cerimonial."),
        alignment: "start",
      },
      {
        id: "capitulo-2",
        date: confirmed("A caminhada"),
        title: confirmed("Dois passos na mesma direção"),
        body: confirmed("O salão claro e o piso antigo dão escala ao momento. Maria e Sérgio aparecem em movimento, como se a página respirasse junto com eles."),
        image: confirmed("/images/wedding/preview/story-palace-walk.jpg"),
        imageAlt: "Maria e Sérgio caminham de mãos dadas em um salão claro.",
        imageTreatment: { desktopPosition: "50% 20%", mobilePosition: "50% 18%", overlay: "none" },
        caption: confirmed("Movimento leve dentro de uma arquitetura clássica."),
        alignment: "end",
      },
      {
        id: "capitulo-3",
        date: confirmed("A promessa"),
        title: confirmed("Calma antes da celebração"),
        body: confirmed("Na varanda, o enquadramento fica mais próximo e contemplativo. A fotografia encerra a sequência com delicadeza, antes da celebração ganhar forma."),
        image: confirmed("/images/wedding/preview/story-balcony-quiet.jpg"),
        imageAlt: "Maria e Sérgio juntos em uma varanda, em um momento tranquilo.",
        imageTreatment: { desktopPosition: "50% 18%", mobilePosition: "50% 16%", overlay: "olive" },
        caption: confirmed("Um retrato íntimo para fechar a narrativa."),
        alignment: "start",
      },
    ],
  },
  venues: [
    {
      id: "ceremony",
      eyebrow: "Cerimônia",
      name: "Paróquia Nossa Senhora de Nazaré",
      city: confirmed("Cabedelo"),
      region: confirmed("Paraíba"),
      time: confirmed("15:30"),
      address: confirmed("Avenida Coronel Cardoso, 15 — Portal do Poço, Cabedelo"),
      note: confirmed("Será uma alegria receber você para testemunhar este momento."),
      directionsUrl: pending("BLOCKED — exact Google Maps URL required from user"),
      directionsLabel: "Como chegar",
      illustration: confirmed("/images/wedding/venues/ceremony-church-clean.png"),
    },
    {
      id: "reception",
      eyebrow: "Recepção",
      name: "Buffet Doce Mel",
      city: confirmed("João Pessoa"),
      region: confirmed("Paraíba"),
      time: pending(""),
      address: confirmed("Rua Manuel Miguel Morais, 54 — Bancários, João Pessoa"),
      note: confirmed("Depois do sim, a celebração continua."),
      directionsUrl: pending("BLOCKED — exact Google Maps URL required from user"),
      directionsLabel: "Como chegar",
      illustration: confirmed("/images/wedding/venues/reception-buffet-doce-mel.png"),
    },
  ],
  schedule: {
    eyebrow: "Programação",
    title: "O ritmo da celebração",
    items: [
      {
        id: "cerimonia",
        time: pending(""),
        title: "Cerimônia",
        description: confirmed("Paróquia Nossa Senhora de Nazaré"),
        icon: "church",
      },
      {
        id: "recepcao",
        time: pending(""),
        title: "Recepção",
        description: confirmed("Buffet Doce Mel"),
        icon: "celebration",
      },
    ],
  },
  dressCode: {
    eyebrow: "TRAJE",
    title: "Para celebrar conosco",
    introduction: confirmed("Sugerimos traje social ou esporte fino elegante. Pedimos apenas que os tons reservados ao cortejo sejam evitados."),
    groups: [
      { id: "general", label: "Convidados", guidance: confirmed("Social ou esporte fino, com elegância e conforto.") },
      { id: "guests", label: "Cores reservadas", guidance: confirmed("Cores reservadas aos padrinhos: verde oliva e cinza claro.") },
    ],
    notes: confirmed(""),
    swatches: [],
  },
  gallery: {
    eyebrow: "Galeria",
    title: "Retratos de uma espera bonita",
    introduction: confirmed("Uma seleção curta, feita para variar distância, gesto e atmosfera sem transformar a página em um álbum completo."),
    items: [],
  },
  rsvp: {
    eyebrow: "CONFIRMAÇÃO DE PRESENÇA",
    title: "RSVP",
    introduction: "Confirme sua presença com carinho para nos ajudar a preparar cada detalhe.",
    modeEnvironmentVariable: "NEXT_PUBLIC_RSVP_MODE",
    defaultMode: "endpoint",
    maxGuests: pending<number>(""),
    labels: {
      guestSearch: "Quem está confirmando presença?",
      guestSearchHelp: "Digite o nome e selecione-o na lista.",
      guestSearchLoading: "Buscando convidados...",
      guestSearchMinimum: "Digite pelo menos 2 caracteres.",
      guestSearchEmpty: "Nenhum convidado encontrado.",
      guestSearchSelected: "Convidado selecionado",
      guestSearchRemove: "Remover convidado",
      phone: "Telefone",
      email: "E-mail",
      message: "Recadinho para os noivos",
      submit: "Confirmar presença",
      submitting: "Enviando...",
    },
    messages: {
      required: "Preencha este campo.",
      invalidEmail: "Informe um e-mail válido.",
      invalidPhone: "Informe um telefone válido.",
      guestsRequired: "Selecione pelo menos um convidado.",
      guestSearchFailed: "Não foi possível buscar convidados agora.",
      guestSearchDuplicate: "Este convidado já foi selecionado.",
      demo: "Os dados foram validados em modo de demonstração.",
      success: "Presença confirmada.",
      endpointMissing: "O canal de confirmação ainda não está configurado. Nenhum dado foi enviado.",
      genericError: "Não foi possível enviar a confirmação. Tente novamente mais tarde.",
    },
  },
  gifts: {
    eyebrow: "PRESENTES",
    title: "Lista de presentes",
    message: confirmed("Sua presença já é muito especial para nós. Se desejar nos presentear, preparamos algumas opções com muito carinho — e um pouco de bom humor."),
    platform: pending("Plataforma de casamento a definir"),
    stores: [],
    items: [
      { id: "aposentadoria", title: "Ajuda para a aposentadoria dos noivos", price: "R$3.194,99", image: { src: "/images/gifts/original/01-aposentadoria.jpg", alt: "Imagem cômica de pessoa descansando enrolada em cobertor para representar a aposentadoria dos noivos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "bebe", title: "Aluguel de um bebê para treinamento", price: "R$333,35", image: { src: "/images/gifts/original/02-aluguel-bebe.jpg", alt: "Imagem cômica de bebê para treinamento dos noivos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "frigobar", title: "Assaltar o frigobar na lua de mel", price: "R$271,18", image: { src: "/images/gifts/original/03-frigobar-lua-de-mel.jpg", alt: "Imagem cômica de frigobar para lua de mel.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "cobertor", title: "Cobertor para a noiva que está sempre coberta de razão", price: "R$120,94", image: { src: "/images/gifts/original/04-cobertor-razao.jpg", alt: "Imagem cômica de pessoa coberta por cobertor.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "controles", title: "Conjunto de controle remotos para não ter briga", price: "R$209,01", image: { src: "/images/gifts/original/05-controles-remotos.jpg", alt: "Imagem cômica relacionada a controle remoto e disputa do casal.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "ar-condicionado", title: "Cota do ar condicionado pra não derreter nesse calor", price: "R$136,48", image: { src: "/images/gifts/original/06-ar-condicionado.jpg", alt: "Imagem cômica sobre calor e ar condicionado.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "filhos", title: "Cota para perguntar quando teremos filhos", price: "R$552,78", image: { src: "/images/gifts/original/07-quando-teremos-filhos.jpg", alt: "Imagem cômica relacionada à pergunta sobre filhos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "geladeira", title: "Deus abençoou e você vai dar a geladeira", price: "R$3.143,19", image: { src: "/images/gifts/original/08-geladeira.jpg", alt: "Imagem cômica para o presente geladeira.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "jantar-noivo", title: "Garanta o jantar do noivo durante o 1º mês de casado", price: "R$635,67", image: { src: "/images/gifts/original/09-jantar-noivo.jpg", alt: "Imagem cômica relacionada ao jantar do noivo.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "buffet", title: "Garantir o primeiro lugar na fila do buffet", price: "R$177,92", image: { src: "/images/gifts/original/10-fila-buffet.jpg", alt: "Foto de buffet para representar a disputa pelo primeiro lugar na fila.", width: 960, height: 720, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "panelas", title: "Jogo de panelas para Sérgio sempre fazer o jantar", price: "R$157,20", image: { src: "/images/gifts/original/11-panelas-sergio.jpg", alt: "Imagem cômica de panelas e cozinha para Sérgio fazer jantar.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "lava-seca", title: "Lava e seca pra não ter briga de quem estende a roupa", price: "R$1.278,09", image: { src: "/images/gifts/original/12-lava-seca.jpg", alt: "Imagem cômica de lava e seca para evitar briga sobre roupa.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "maquiagem", title: "Lenço para a noiva não borrar toda a maquiagem", price: "R$85,19", image: { src: "/images/gifts/original/13-lenco-maquiagem.jpg", alt: "Imagem cômica de noiva chorando para representar o lenço da maquiagem.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "maracuja", title: "Maracujá para os noivos ficarem tranquilos", price: "R$89,85", image: { src: "/images/gifts/original/14-maracuja.jpg", alt: "Imagem cômica de maracujá para tranquilidade dos noivos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "financiamento", title: "Menos uma parcela no financiamento do AP", price: "R$967,25", image: { src: "/images/gifts/original/15-financiamento-ap.jpg", alt: "Imagem cômica relacionada ao financiamento do apartamento.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "passeio", title: "Passeio na lua de mel", price: "R$428,44", image: { src: "/images/gifts/original/16-passeio-lua-de-mel.jpg", alt: "Imagem cômica de passeio para a lua de mel.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "despedida-noiva", title: "Patrocine a despedida da noiva", price: "R$511,33", image: { src: "/images/gifts/original/17-despedida-noiva.jpg", alt: "Imagem cômica de despedida da noiva.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "despedida-noivo", title: "Patrocine a despedida do noivo", price: "R$473,00", image: { src: "/images/gifts/original/18-despedida-noivo.jpg", alt: "Imagem cômica de despedida do noivo.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "ir-junto", title: "Poder ir junto com os noivos para a lua de mel", price: "R$86.036,15", image: { src: "/images/gifts/original/19-ir-junto-lua-de-mel.jpg", alt: "Imagem cômica de pessoa segurando vela para acompanhar a lua de mel.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "presenteao", title: "Presentão para os noivos", price: "R$397,36", image: { src: "/images/gifts/original/20-presentao.jpg", alt: "Imagem cômica de presentão para os noivos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "quarto-visita", title: "Prioridade no quarto de visita na casa dos noivos", price: "R$791,10", image: { src: "/images/gifts/original/21-quarto-visita.jpg", alt: "Imagem cômica de quarto de visita na casa dos noivos.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "relogio", title: "Relógio para a noiva parar de se atrasar", price: "R$250,46", image: { src: "/images/gifts/original/22-relogio-noiva.jpg", alt: "Imagem cômica de relógio para a noiva parar de se atrasar.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "tampao", title: "Tampão de ouvido pra noiva enquanto noivo ronca", price: "R$105,39", image: { src: "/images/gifts/original/23-tampao-ronco.jpg", alt: "Imagem cômica de tampão de ouvido para ronco do noivo.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "buque", title: "Taxa pra noiva jogar o buquê na sua direção", price: "R$229,73", image: { src: "/images/gifts/original/24-buque-direcao.jpg", alt: "Imagem cômica de noiva jogando buquê.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "cabelo", title: "Um ano de cabelo cortado para o noivo", price: "R$418,08", image: { src: "/images/gifts/original/25-cabelo-noivo.jpg", alt: "Imagem cômica de barbearia para o corte de cabelo do noivo.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente" },
      { id: "valor-livre", title: "Não achou o presente perfeito?", description: "Escolha o valor. A gente promete usar com sabedoria. Talvez.", price: "Valor livre", image: { src: "/images/gifts/original/26-valor-livre.svg", alt: "Envelope de presente para valor livre.", width: 600, height: 600, status: "confirmed" }, paymentLabel: "Escolher este presente", customAmount: true },
    ],
    pendingMessage: "Escolha uma das opções abaixo.",
  },
  travel: {
    enabled: false,
    eyebrow: "Viagem e hospedagem",
    title: "Para quem vem de longe",
    introduction: pending(""),
    airport: pending(""),
    transportation: pending(""),
    hotels: pending<string[]>(""),
    beaches: pending<string[]>(""),
    recommendations: pending<string[]>(""),
    contact: pending(""),
  },
  closing: {
    eyebrow: "ATÉ O NOSSO GRANDE DIA",
    thankYou: "Que alegria poder viver tudo isso ao lado de quem amamos.",
    names: "Maria & Sérgio",
    date: "31 de outubro de 2026",
    calendar: {
      allDay: true,
      eventTitle: "Casamento de Maria e Sérgio",
      description: confirmed("Celebração do casamento de Maria e Sérgio."),
      location: confirmed("Paróquia Nossa Senhora de Nazaré, Cabedelo, Paraíba"),
      googleCalendarUrl: pending("Gerado pela interface a partir dos dados confirmados"),
      downloadLabel: "Adicionar ao calendário",
    },
    backToTopLabel: "Voltar ao início",
  },
  personalization: {
    enabled: false,
    allowedQueryParameters: { guestName: "convidado", maximumCompanions: "acompanhantes" },
  },
  features: {
    showStory: false,
    showSchedule: false,
    showDressCode: true,
    showGallery: false,
    showRsvp: true,
    showGifts: true,
    showTravel: false,
    showAudioControl: true,
  },
} satisfies WeddingContent;

export default weddingContent;
